### ISSUE TITLE
AttributeError: 'function' object has no attribute 'get_chats'

### ISSUE THREAD

**Issue by Nutr1t07** [milkice233/efb-qq-slave#39]
# 问题描述
启动服务后向Telegram机器人发送任何指令均无作用，且转发服务无法运行。VNC成功运行且已登陆QQ账号，酷Q机器人正常运行并可执行互动式向导，在ehforwarderbot日志中发现AttributeError。
# 重现步骤
1. `sslocal -c /etc/shadowsocks/config.json &`
2. 
```
    docker run -ti --rm --name cqhttp-test --net="host" \
     -v $(pwd)/coolq:/home/user/coolq     \
     -p 9000:9000                                         \
     -p 5700:5700                                         \
     -e VNC_PASSWD=blahblah                    \
     -e COOLQ_PORT=5700                         \
     -e COOLQ_ACCOUNT=123456789    \
     -e CQHTTP_POST_URL=http://127.0.0.1:8000    \
     -e CQHTTP_SERVE_DATA_FILES=yes     \
     -e CQHTTP_ACCESS_TOKEN=ac0f790e1fb74ebcaf45da77a6f9de47  \
     -e CQHTTP_POST_MESSAGE_FORMAT=array   \
     richardchien/cqhttp:latest
```

3. `proxychains ehforwarderbot`
4. 向Telegram机器人发送“/chat”

# 日志
- docker
```
WARNING: Published ports are discarded when using host network mode
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 010-app: applying... 
[fix-attrs.d] 010-app: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 010-setup-vnc: executing... 
Would you like to enter a view-only password (y/n)? Password:Verify:[cont-init.d] 010-setup-vnc: exited 0.
[cont-init.d] 020-setup-sudo: executing... 
[cont-init.d] 020-setup-sudo: exited 0.
[cont-init.d] 110-get-coolq: executing... 
CoolQ already exists, skip download.
DEBUG: 插件版本已锁定，开始覆盖 cpk 文件……
INFO: CoolQ HTTP API 插件 bootstrap 完成。
[cont-init.d] 110-get-coolq: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
xauth:  file /home/user/.Xauthority does not exist
WebSocket server settings:
  - Listen on :9001
  - No SSL/TLS support (no cert file)
  - proxying from :9001 to 127.0.0.1:5911

New 'iZuf6i3xfl9zacvzwqpz8vZ:11 (user)' desktop is iZuf6i3xfl9zacvzwqpz8vZ:11

Creating default startup script /home/user/.vnc/xstartup
Creating default config /home/user/.vnc/config
Starting applications specified in /home/user/.vnc/xstartup
Log file is /home/user/.vnc/iZuf6i3xfl9zacvzwqpz8vZ:11.log

[CQDaemon] Starting CoolQ ....
[CQDaemon] Started CoolQ .
[2019-09-14 04:00:06.109] [I] [日志] 日志控制台开启成功
[2019-09-14 04:00:06.115] [I] [HTTP] 开启 HTTP 服务器成功，开始监听 http://[::]:5700
[2019-09-14 04:00:06.136] [I] [HTTP] 通过 HTTP 上报数据到 http://127.0.0.1:8000 成功，状态码：200
```
- ehforwarderbot
```
ProxyChains-3.1 (http://proxychains.sf.net)
2019-09-14 10:59:08,037 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:85)
     Initializing slave milkice.qq... 
2019-09-14 10:59:08,045 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:96)
     Slave channel QQ Slave (milkice.qq) # Default profile is initialized. 
2019-09-14 10:59:08,045 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:99)
     Initializing master blueset.telegram... 
|DNS-request| api.telegram.org 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| api.telegram.org is 149.154.167.220
|S-chain|-<>-127.0.0.1:1080-<><>-149.154.167.220:443-<><>-OK
2019-09-14 10:59:10,373 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:109)
     Master channel Telegram Master (blueset.telegram) # Default profile is initialized. 
2019-09-14 10:59:10,373 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:111)
     All channels initialized. 
2019-09-14 10:59:10,373 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:125)
     All middlewares are initialized. 
|S-chain|-<>-127.0.0.1:1080- * Serving Flask app "cqhttp" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
<><>-127.0.0.1:5700-<><>-OK
|DNS-request| api.telegram.org 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| api.telegram.org is 149.154.167.220
|S-chain|-<>-127.0.0.1:1080-<><>-149.154.167.220:443-<><>-OK
2019-09-14 11:00:55,508 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/nutr1t07/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/nutr1t07/.local/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/nutr1t07/.local/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 678, in start_chat_list
    return self.chat_head_req_generate(bot, target, pattern=" ".join(args), chats=chats)
  File "/home/nutr1t07/.local/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 727, in chat_head_req_generate
    source_chats=chats)
  File "/home/nutr1t07/.local/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 330, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/home/nutr1t07/.local/lib/python3.6/site-packages/efb_qq_slave/__init__.py", line 94, in get_chats
    return self.QQClient.get_chats()
AttributeError: 'function' object has no attribute 'get_chats'
```

# 环境
- **Ubuntu** 18.04.3 LTS (GNU/Linux 4.15.0-63-generic x86_64)
- **ehforwarderbot** 2.0.0b19
- **efb-telegram-master** 2.0.0b25
- **efb-qq-slave** 2.0.0a10
- **richardchien/cqhttp:latest** 2019-09-09T13:40:03.884800217Z

并依照 https://milkice.me/2018/09/17/efb-how-to-send-and-receive-messages-from-qq-on-telegram/ 步骤安装。

**Comment by Nutr1t07** [comment]
# 配置文件
- ~/.ehforwarderbot/profiles/default/config.yaml
```
master_channel: blueset.telegram
slave_channels:
- milkice.qq
```
- ~/.ehforwarderbot/profiles/default/milkice.qq/config.yaml
```
Client: CoolQ                         # 指定要使用的 QQ 客户端（此处为CoolQ）
CoolQ:
    type: HTTP
    access_token: ac0f790e1fb74ebcaf45da77a6f9de47
    api_root: http://127.0.0.1:5700/
    host: 127.0.0.1
    port: 8000
    is_pro: false
    air_option:
        upload_to_smms: true
```
- ~/.ehforwarderbot/profiles/default/blueset.telegram/config.yaml
```
token: "xxx"
admins:
- 123456789
```

**Comment by Nutr1t07** [comment]
或许与此issue中提到的接口失效有关 https://github.com/richardchien/coolq-http-api/issues/207

**Comment by milkice233** [comment]
> 或许与此issue中提到的接口失效有关 [richardchien/coolq-http-api#207](https://github.com/richardchien/coolq-http-api/issues/207)

不是这个的问题，已经有 workaround 了

**Comment by milkice233** [comment]
所以能否看下 /home/nutr1t07/.local/lib/python3.6/site-packages/efb_qq_slave/Clients/CoolQ/CoolQ.py 的内容呢

**Comment by Nutr1t07** [comment]
> 所以能否看下 /home/nutr1t07/.local/lib/python3.6/site-packages/efb_qq_slave/Clients/CoolQ/CoolQ.py 的内容呢

https://gist.github.com/Nutr1t07/7ef03cf263009dbd2b5986b33bc6c59a

**Comment by Nutr1t07** [comment]
发送/chat后只回复"Processing..."
![Screenshot_20190915_085008](https://user-images.githubusercontent.com/30677291/64915312-8cdef900-d796-11e9-856d-bfd421eaf797.png)

另外从QQ发送消息会提示如下信息
![Screenshot_20190915_085041](https://user-images.githubusercontent.com/30677291/64915316-9ec09c00-d796-11e9-8be3-fecb7663bcfc.png)

定期检查显示
![Screenshot_20190915_085453](https://user-images.githubusercontent.com/30677291/64915318-a5e7aa00-d796-11e9-9574-a9bed8e5969b.png)

**Comment by milkice233** [comment]
这就很奇怪了...get_chats() 方法明明就在 CoolQ.py 里没错啊
如果不在 proxychains4 环境里运行试试呢

**Comment by Nutr1t07** [comment]
> 如果不在 proxychains4 环境里运行试试呢

同样无法修复...但是我已经用另外一个运行在酷Q的插件了

**Comment by milkice233** [comment]
@Nutr1t07 可否说下是哪个插件呢 有点好奇

**Comment by Nutr1t07** [comment]
@milkice233 https://github.com/JogleLew/coolq-telegram-bot-x
