### ISSUE TITLE
ehforwarderbot无法启动 提示无法载入EFBChannel模块

### ISSUE THREAD

**Issue by 1715173329** [milkice233/efb-qq-slave#49]
报错信息如下：
```python3
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 263, in main
    conf = config.load_config()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 60, in load_config
    channel = utils.locate_module(i, 'slave')
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/utils.py", line 145, in locate_module
    return i.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_slave/__init__.py", line 11, in <module>
    from ehforwarderbot import EFBChannel, ChannelType, EFBMsg, EFBStatus, EFBChat, MsgType
ImportError: cannot import name 'EFBChannel'
```
基本依赖已安装并满足要求，确认配置文件无误。

**Comment by milkice233** [comment]
EFB 2.0.0b26 重构了 API，EQS这边也在抓紧重构，但尚未完成
你可以选择，将EFB降级到2.0.0b26之前（如果目前急需使用，推荐这个），或者使用 本项目的 EFB_2.0.0b26 分支，也就是正在重构的分支，尚不稳定还有很多bug没修

**Comment by 1715173329** [comment]
OK，已解决，非常感谢您的帮助。
