### ISSUE TITLE
efb初始化从端失败

### ISSUE THREAD

**Issue by Orokapei** [milkice233/efb-qq-slave#83]
````
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ehforwarderbot/__main__.py", line 339, in main
    init(conf)
  File "/usr/local/lib/python3.9/dist-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.9/dist-packages/efb_qq_slave/__init__.py", line 44, in __init__
    self.init_client_manager()
  File "/usr/local/lib/python3.9/dist-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
    self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
  File "/usr/local/lib/python3.9/dist-packages/efb_qq_slave/ClientMgr.py", line 20, in __init__
    c = importlib.import_module('.' + name, actual_path + '.Clients.' + name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'efb_qq_slave.Clients.mirai'
````
mirai启动正常，mirai-api-http也正常启用了
````
I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8081
I/Mirai HTTP API: Http api server is running with authKey: 1270018081
I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
I/net.mamoe.mirai-api-http: 上报模块启用状态: true
````
eqs配置如下
````
Client: mirai
mirai:
    qq: xxxxxxxxxx
    host: "0.0.0.0"
    port: 8081
    authKey: "1270018081"
````

**Comment by milkice233** [comment]
整个项目还在测试，请从 Github 上拉源代码
`pip3 install git+https://github.com/milkice233/efb-qq-slave`

**Comment by Orokapei** [comment]
> 整个项目还在测试，请从 Github 上拉源代码
> `pip3 install git+https://github.com/milkice233/efb-qq-slave`

啊，感谢，可以了ovo
