### ISSUE TITLE
新版 (pypi 2.0.1) 使用telegram回复自己发送的消息报错

### ISSUE THREAD

**Issue by TTTPOB** [milkice233/efb-qq-slave#89]

**Comment by TTTPOB** [comment]
```
Traceback (most recent call last):
  File "/home/xxxxx/tools/qqforwarding/.venv/local/lib/python3.9/site-packages/efb_telegram_master/master_message.py", line 393, in process_telegram_message
    slave_msg = coordinator.send_message(m)
  File "/home/xxxxx/tools/qqforwarding/.venv/local/lib/python3.9/site-packages/ehforwarderbot/coordinator.py", line 113, in send_message
    return slaves[msg.deliver_to.channel_id].send_message(msg)
  File "/home/xxxxx/tools/qqforwarding/.venv/local/lib/python3.9/site-packages/efb_qq_slave/__init__.py", line 80, in send_message
    return self.QQClient.send_message(msg)
  File "/home/xxxxx/tools/qqforwarding/.venv/local/lib/python3.9/site-packages/efb_qq_plugin_mirai/mirai.py", line 187, in send_message
    messages.append(At(target=int(uin), display="@"))
ValueError: invalid literal for int() with base 10: ''
```
