### ISSUE TITLE
efb启动失败

### ISSUE THREAD

**Issue by lq-259** [milkice233/efb-qq-slave#93]
2021-07-12 13:01:48,867 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:129)
     正在初始化从端 milkice.qq…
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_slave/ClientMgr.py", line 27, in __init__
    self.client = cls(name, config, channel)
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_plugin_iot/IOTBot.py", line 52, in __init__
    self.uin = self.client_config['qq']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_slave/__init__.py", line 44, in __init__
    self.init_client_manager()
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
    self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
  File "/usr/local/lib/python3.6/dist-packages/efb_qq_slave/ClientMgr.py", line 30, in __init__
    raise Exception("Specified client not found!")
Exception: Specified client not found!

**Comment by milkice233** [comment]
贴下日志？感觉配置里Client写错了

**Comment by lq-259** [comment]
> 贴下日志？感觉配置里Client写错了

不好意思，忘了关闭了，虽然忘了是什么原因但已经解决了
