### ISSUE TITLE
初始化客户端报错(mirai/opq都可以, 但是go-cqhttp不行)

### ISSUE THREAD

**Issue by wqk317** [milkice233/efb-qq-slave#95]
我的issue提错地方了, 大家凑合看吧
https://github.com/XYenon/efb-qq-plugin-go-cqhttp/issues/7

**Comment by wqk317** [comment]
上边的问题已经搞定, 但是`ehforwarderbot`那边一直报错...
```
2021-08-04 15:30:03,191 [ERROR]: cqhttp (app.log_exception; app.py:1454)
    Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 101, in _handle
    response = handler(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 150, in handle_msg
    user = self.get_user_info(qq_uid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 603, in get_user_info
    user['is_friend'] = False
TypeError: 'NoneType' object does not support item assignment
2021-08-04 15:30:04,433 [ERROR]: cqhttp (app.log_exception; app.py:1454)
    Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 101, in _handle
    response = handler(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 150, in handle_msg
    user = self.get_user_info(qq_uid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 603, in get_user_info
    user['is_friend'] = False
TypeError: 'NoneType' object does not support item assignment
2021-08-04 15:30:20,462 [ERROR]: cqhttp (app.log_exception; app.py:1454)
    Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 101, in _handle
    response = handler(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 150, in handle_msg
    user = self.get_user_info(qq_uid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 603, in get_user_info
    user['is_friend'] = False
TypeError: 'NoneType' object does not support item assignment
2021-08-04 15:30:21,057 [ERROR]: cqhttp (app.log_exception; app.py:1454)
    Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 101, in _handle
    response = handler(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 150, in handle_msg
    user = self.get_user_info(qq_uid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 603, in get_user_info
    user['is_friend'] = False
TypeError: 'NoneType' object does not support item assignment
2021-08-04 15:30:23,583 [ERROR]: cqhttp (app.log_exception; app.py:1454)
    Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 101, in _handle
    response = handler(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 150, in handle_msg
    user = self.get_user_info(qq_uid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 603, in get_user_info
    user['is_friend'] = False
TypeError: 'NoneType' object does not support item assignment
2021-08-04 15:30:25,831 [ERROR]: cqhttp (app.log_exception; app.py:1454)
    Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 101, in _handle
    response = handler(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 150, in handle_msg
    user = self.get_user_info(qq_uid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 603, in get_user_info
    user['is_friend'] = False
TypeError: 'NoneType' object does not support item assignment
2021-08-04 15:30:28,112 [ERROR]: cqhttp (app.log_exception; app.py:1454)
    Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 101, in _handle
    response = handler(event)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cqhttp/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 150, in handle_msg
    user = self.get_user_info(qq_uid)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 603, in get_user_info
    user['is_friend'] = False
TypeError: 'NoneType' object does not support item assignment
```
