### ISSUE TITLE
ENGINE Bus STARTED 後重複報錯

### ISSUE THREAD

**Issue by AkazaRenn** [milkice233/efb-qq-slave#99]
```
[01/Dec/2021:04:57:44] ENGINE Bus STARTING
[01/Dec/2021:04:57:44] ENGINE Started monitor thread 'Autoreloader'.
[01/Dec/2021:04:57:44] ENGINE Serving on http://127.0.0.1:8000
[01/Dec/2021:04:57:44] ENGINE Bus STARTED
2021-12-01 04:57:44,736 [ERROR]: cqhttp (app.log_exception; app.py:1891)
    Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/cqhttp/__init__.py", line 91, in _handle
    type_ = event.get('post_type', '')
AttributeError: 'NoneType' object has no attribute 'get'
```

用的 go-cqhttp 模式，以下是配置文件：
```yaml
Client: GoCQHttp                         # 指定要使用的 QQ 客户端（此处为CoolQ）
GoCQHttp:
  type: HTTP                        # 指定 efb-qq-plugin-go-cqhttp 与 GoCQHttp 通信的方式 现阶段仅支持 HTTP
  access_token: ############################
  api_root: http://127.0.0.1:5700/  # GoCQHttp API接口地址/端口
  host: 127.0.0.1                   # efb-qq-slave 所监听的地址用于接收消息
  port: 8000                        # 同上
```

**Comment by AkazaRenn** [comment]
好像是 plugin 那邊的問題
